
if(window.location.pathname.includes("admin.html")){if(localStorage.getItem("isAdmin")!=="true"){alert("🚫 Access denied! Please login first.");window.location.href="login.html";}}
function convertTo12Hour(t){if(!t)return"—";const[h,m]=t.split(':').map(Number);return`${(h%12||12).toString().padStart(2,'0')}:${m.toString().padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function displayBookings(){const t=document.querySelector("#bookingTable tbody");if(!t)return;t.innerHTML="";let b=JSON.parse(localStorage.getItem("bookings"))||[];if(b.length===0){document.getElementById("emptyState").style.display="block";return}document.getElementById("emptyState").style.display="none";b.forEach((bk,i)=>{const ci=new Date(bk.checkIn).toLocaleDateString(),co=new Date(bk.checkOut).toLocaleDateString(),sd=bk.days===1&&bk.timeIn&&bk.timeOut,ti=sd?convertTo12Hour(bk.timeIn):"—",to=sd?convertTo12Hour(bk.timeOut):"—";let d="—";if(sd&&bk.timeIn&&bk.timeOut){const[ih,im]=bk.timeIn.split(':').map(Number),[oh,om]=bk.timeOut.split(':').map(Number);let s=oh*60+om-ih*60-im;if(s<0)s+=24*60;const hr=Math.floor(s/60),mn=s%60;d=mn>0?`${hr}h ${mn}m`:`${hr}h`}t.innerHTML+=`<tr><td>${escapeHtml(bk.name)}</td><td>${escapeHtml(bk.email)}</td><td>${escapeHtml(bk.phone)}</td><td>${escapeHtml(bk.event)}</td><td>${ci}</td><td>${co}</td><td>${ti}</td><td>${to}</td><td><strong>${d}</strong></td><td style="font-weight:700;text-align:center;">${bk.guests}</td><td style="font-weight:700;text-align:center;">${bk.days}</td></tr>`});displayDeleteTable()}
function displayDeleteTable(){const d=document.querySelector("#deleteTable tbody");if(!d)return;d.innerHTML="";let b=JSON.parse(localStorage.getItem("bookings"))||[];b.forEach((bk,i)=>{d.innerHTML+=`<tr><td>${escapeHtml(bk.name)}</td><td><button class="btn btn-small btn-danger" onclick="deleteBooking(${i})">Delete</button></td></tr>`})}
window.deleteBooking=function(i){if(confirm("Are you sure you want to delete this booking?")){let b=JSON.parse(localStorage.getItem("bookings"))||[];b.splice(i,1);localStorage.setItem("bookings",JSON.stringify(b));displayBookings();alert("✅ Booking deleted successfully!")}}
function logout(){if(confirm("Are you sure you want to logout?")){localStorage.removeItem("isAdmin");alert("✅ Logged out successfully!");window.location.href="login.html"}}
function login(){let u=document.getElementById("username").value.trim(),p=document.getElementById("password").value;if(!u||!p){alert("❌ Please enter both username and password!");return}if(u==="admin"&&p==="1234"){localStorage.setItem("isAdmin","true");alert("✅ Login successful!");window.location.href="admin.html"}else{alert("❌ Invalid credentials!\nTry: username: admin | password: 1234")}}
function escapeHtml(t){const m={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'};return t.replace(/[&<>"']/g,c=>m[c])}
function updateStats(){const b=JSON.parse(localStorage.getItem("bookings"))||[],tg=b.reduce((s,bk)=>s+parseInt(bk.guests),0),td=b.reduce((s,bk)=>s+parseInt(bk.days),0);document.getElementById("statsBar").innerHTML=`<div class="stat-card"><div class="stat-icon">📊</div><div class="stat-label">Total Bookings</div><div class="stat-value">${b.length}</div></div><div class="stat-card"><div class="stat-icon">👥</div><div class="stat-label">Total Guests</div><div class="stat-value">${tg}</div></div><div class="stat-card"><div class="stat-icon">📅</div><div class="stat-label">Total Days</div><div class="stat-value">${td}</div></div>`}
document.addEventListener('DOMContentLoaded',function(){if(document.getElementById("statsBar")){updateStats();displayBookings()}})